services:
    server:
        command: npm run dev
    
    worker:
        command: npm run dev

    client-dev:
        container_name: client-dev
        image: node:20-alpine
        working_dir: /app
        command: sh -c "npm install && npm run dev -- --host"
        ports:
            - '5173:5173'
        env_file: ./.env
        volumes:
            - ./client:/app