services:
    server:
        command: npm run dev
    
    worker:
        command: npm run dev

    client-build:
        command: sh -c "npm install && npm run dev -- --host"
        ports:
            - '5173:5173'